### ISSUE TITLE
Showing operational state.

### ISSUE THREAD

**Issue by edegraaff** [rffrasca/PDFKeeper#39] opened 2024-11-02 22:25 UTC
**Is your feature request related to a problem? Please describe.**
Not realy a problem, but when processing documents i have no clue what the program is dooing.  I have a "washing machine" icon but is the program not responding or just bussy.  

**Describe the solution you'd like**
Some sort of que management or procces  state

**Describe alternatives you've considered**
I am now using the proc mon to see if the program is operational or not when it uses 0% cpu it is in wait for input, when it is in 10% it is dooing something.

**Additional context**
I don;t think they are needed but if thats the case i am able to add them

**Comment by rffrasca** [comment] 2024-11-03 13:26
The upload process and its folder maintenance are asynchronous tasks. This was designed this way to not block the user from using the application while documents are being uploaded. The "green clock" on the status bar will appear while the upload is running to provide status to the user.

**Comment by edegraaff** [comment] 2024-11-09 22:25
ok thanks.
We want for your association procces 100 or more pdf docs to have an index from all the work done over the last 15 years, ... i want to make sure it is processed in the right way. I am still puzzeled abouth the approach, to get it working, the pdf's contain indexes and all kind of subject that have been discussed in the documents over the years.

**Comment by rffrasca** [comment] 2024-11-10 16:39
"I want to make sure it is processed in the right way."
Are you looking for logging to be added to the upload process?

**Comment by rffrasca** [comment] 2024-11-10 21:48
Another user opened a request for a progress bar during the upload process. Would this be helpful for you and address your issue? I was thinking a marquee style progress bar that would appear on the status bar during the upload. This progress bar would replace the "green clock".

**Comment by edegraaff** [comment] 2024-11-10 22:38
Hi, i think somthing that gives you insights in the progress of importing the pdf's would be great. On the another hand, i am also searching for some more advanced functions. We are trying to get an overview over all the journals that have been published over the time, and hashtags or other markers to search on, or index on could be needed. I understand you never developed the program for this purpose and maybee i need to use something else. But beeing able to see progress and als to add special words to search and or index could be practical, in your tax example i want to see everything for year 2020, or everything related to healthcare, or, buy equipment. For us as a non profit organisation we want to serve our members to look back in the past what interesing articles have been published about what subject.  Regards Eelco

**Comment by rffrasca** [comment] 2024-11-11 02:08
Hi Eelco,
I want to first focus on the upload progress, then we can move on to next part.

When you say "Insights" are you referring to information such as the filename being processed and the operation being performed on each page like text extraction, OCR, etc.?

**Comment by edegraaff** [comment] 2024-11-11 15:05
Yes something like that, it could be somewhere a progress bar, and or logging file that says: picking up "filename.pdf", processing ocr, storing, indexing, done, next ... it all depends on time and effort you want to put in this. I could imagine when you have 100 files in the inbox, you will poll lets say every 10 seconds. i drop 100 files, then you get something for i is 1 to 100, and then you could make a progrebar or an counter. The issue is, time... when you procces a lot of files, and someone adds new ones... on the another hand who cares. Hum, what about this approach: poll inbox, pickup file, and count files ok there are 100 files there, processing one of 100, proces is ready, do next poll, count files, 10 added, ok counting 99+10 and count from there... after a while the inbox is empty system in steady state... i am not a programmer, so i have no clue what problems you will find if you build something like this ... 
keep it simple :-|)

**Comment by rffrasca** [comment] 2024-11-12 01:10
Thanks for the detailed explanation, what that I came up with the following solution:

I will be implementing a marquee style progress bar for another request that will be visible when the upload is running. So, for your request, I was thinking of:

- Adding to the status bar, a message like this "Uploading PDF # of #" that would be visible during the upload.
- I was also thinking of logging the upload with "Processing <PATH>\filename.pdf" and for each page, log messages like "Extracting PDF properties.", "Extracting text annotations". For each page, log status such as "Page 1 extracting text", or "Page 1 extracting text using OCR.". When a page is not processed, that will be logged also.
- During each upload cycle, a new log will be created that can be viewed using a log viewer that I can add to the application. The log viewer could have a Delete button that you can use to delete the log after you have reviewed it.

If you like this plan, give it a thumbs up and I will schedule it in a future release.

**Comment by edegraaff** [comment] 2024-11-12 08:19
Thanks, yes i will, i received some sample documents in all sizes and will play with them. I also figured out how to make a reset on the data and rebuild the content of the database. I will test it later this week thanks!

**Comment by edegraaff** [comment] 2024-11-25 21:54
Hi, thanks for the updated version, i am currently testing it on my notebook. 
To give you some ideas about size and performance: 
![image](https://github.com/user-attachments/assets/93e29509-9f77-4ac5-93ab-50bfb9f49498)
![image](https://github.com/user-attachments/assets/fb1409b5-c99a-44d3-8e68-afaa60c5ac2f)

PDF keeper import from dropping the files in de download foler is fast.
From there the processing is taking quite some time, and the progress indicator is working and also shows the large files do take quite a while to index and ocr and import in the database
![image](https://github.com/user-attachments/assets/3325fa06-2efa-4e0e-9429-d52cc1122960)
I will wait and see, but the first results look ok. 
Regards
Eelco

**Comment by edegraaff** [comment] 2024-11-25 22:23
If the indexing or ocr still gooing on, will PDF keeper warn when you want to close the program if tasks are not yet ready? 
The keywords indes is in my situation empty but it would be great to add here something like #editorial and other subjects that could be easy indexed and found this way ... plans are to demonstrate the results to the team of volonteers that manage the kontactlinjen i think they will be enthousiasic...

**Comment by rffrasca** [comment] 2024-11-26 17:14
Hello Eelco,
The progress indicator was added as a request by another user. I know you were looking for an enhancement with logging and a status bar message. Do you still need this?

When text needs to be extracted from a page using OCR, the process will be lengthy as the page needs to be converted into a 600 DPI TIFF first. The TIFF file will be large and may take a while to create. Next, the TIFF image has to be decoded into a software bitmap for OCR to scan it. This process will occur for each page in the PDF that cannot be processed by iText or does not contain any text. You will see high disk IO and high memory usage during this process. In your screenshot above, the memory usage is 484.9MB which is what I would expect to see.

The Keywords is a property in the PDF Metadata. PDFKeeper can read the value and store in the database where it can be indexed and searched. PDFKeeper can also set the Keywords into the PDF during the upload process. After uploading, Keywords cannot be modified using the UI but, if that is something you need added, feel free to create a feature request for it. I can add a feature that allows setting the keywords in the database for the selected record, it will only update the database, not the PDF.

**Comment by rffrasca** [comment] 2024-11-26 17:29
I forgot to answer your question. When closing, PDFKeeper will prompt to save notes if notes have not been saved. Next, PDFKeeper will check if an upload cycle is still running and wait until it has finished. If you add more PDF's to be upload during an upload cycle, those files will remain in the upload folder until the next time PDFKeeper is opened.

**Comment by rffrasca** [comment] 2024-11-27 14:21
Hi Eelco, as you noted, the PDFs are removed from the import folder quickly. This is because the upload process stages all of the PDFs into the UploadStaging folder as clones with the user specified values applied to the metadata of the PDF. After being staged, the originals are removed using a delete function that deletes to the Windows Recycle Bin. In the staging process is where a PDF could be rejected and moved to the UploadRejected folder. If this was to happen, you will see a "yellow triangle" on the status bar that you can click on to open the UploadRejected folder.

Since you're satisfied with the new progress bar for the upload, I will cancel the logging and status enhancement. If you're all set, I can close this issue. As always, if you encounter any bugs or need enhancements, feel free to open requests.

**Comment by edegraaff** [comment] 2024-11-27 14:32
Fine by me, i think your tool could help the redaction team, and i will do some demonstration in the upcomming weeks. 

I installed the tool standalone, i had a lot of problems with getting the oracle solution working propperly. My idea is to import all the pdfs and there are amost 100 i beleve. Then copy the database and settings files to the redation team members. This makes it quite simple to use the tool and that is what they need, searching in old pdf files.

**Comment by rffrasca** [comment] 2024-11-27 14:47
Thanks for the feedback Eelco! I hope PDFKeeper serves you and your organization well.

**Closed by rffrasca** 2024-11-27 14:47 UTC
Labels: question
